name: 'gha-finops-policies'
description: 'GitHub Action for FinOps policies using OPA'
author: 'Kavinraja-G'

inputs:
  config:
    description: 'YAML-like configuration string'
    required: true

outputs:
  out-file:
    description: 'Path to the generated YAML file'

runs:
  using: node20
  main: dist/index.js
