name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

env:
  CONFTEST_VERSION: 0.49.1
  WORKING_DIR: ./

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install Conftest
        run: |
          wget -O - 'https://github.com/open-policy-agent/conftest/releases/download/v${{ env.CONFTEST_VERSION }}/conftest_${{ env.CONFTEST_VERSION }}_Linux_x86_64.tar.gz' | tar zxvf -
          ./conftest --version
          mv ./conftest /usr/local/bin/

      - name: Test Local Action - for AWS
        id: test-action-aws
        uses: ./
        with:
          inputPath: ${{ env.WORKING_DIR }}test-tfplan.json
          config: |
            kubernetes:
              enabled: false
            aws:
              enabled: true
              ec2:
                enabled: false
                restrictedInstanceTypeRegEx: "large|metal"
              tags:
                enabled: true
                allowedBillingTags:
                  - "FinancialOwner"
                  - "createdBy"

      - name: Test Local Action - for K8s
        id: test-action-k8s
        uses: ./
        with:
          inputPath: ${{ env.WORKING_DIR }}test-deployment.yaml
          config: |
            kubernetes:
              enabled: true
            aws:
              enabled: false

      - name: Print Generated Config
        id: output
        run: |
          cat "${{ steps.test-action-aws.outputs.out-file }}"
          cat "${{ steps.test-action-k8s.outputs.out-file }}"
